[W51-C004] Sublime-text plugins - Maven - update DECK and add workflows - patch 20.
Deck-Link: https://github.com/hoss-java/calapp-workshop/blob/main/DECK.md#51-004
Change-Id: Ic986d72aec85ade668f658c71e898ff3835b5bd4

diff --git a/.github/workflows/generate-deck.yml b/.github/workflows/generate-deck.yml
--- a/.github/workflows/generate-deck.yml
+++ b/.github/workflows/generate-deck.yml
@@ -19,4 +19,8 @@ jobs:
 
       - name: Generate Deck
         run: |
-          bash generate-deck.sh || { echo "Script failed"; exit 1; }
+          bash generate-deck.sh 2>&1 | tee output.log
+          if [ $? -ne 0 ]; then
+            echo "Script failed";
+          exit 1;
+          fi
